config/routes.rb
Rails.application.routes.draw do
 root to: "home#index"
 
 resources :softwares
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/software.rb
class Software < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
    def index
        @softwares = Software.all 
    end

    def new
        @software = Software.new
    end

    def create
      @software = Software.new(params.require(:software).permit(:name, :version))
      if @software.save
        flash[:notice] = 'software registrado com sucesso'
        redirect_to softwares_path
      else
        flash[:alert] = 'Sofware não Registrado'
        render :new
      end
    end

    def show
      @software = Software.find(params[:id])

    end

    def edit
      @software = Software.find(params[:id])
    end

    def update
      @software = Software.find(params[:id])
      if @software.update(params.require(:software).permit(:name, :version))
        redirect_to softwares_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      software = Software.find(params[:id])
      software.destroy
      redirect_to softwares_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/home/index.html.erb
<h1> Bem vindo </h1>


<%= button_to'Cadastro', new_software_path, method: :get %><br>
<%= button_to 'lista', softwares_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pclist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/softwares/_form.html.erb
<%= form_with model: @software do |s| %>
    <div>
    <%= s.label :name, 'Nome' %>
    <%= s.text_field :name %>
    </div>
    <div>
    <%= s.label :version, 'Versão' %>
    <%= s.text_field :version %>
    </div>
    <div>
    <%= s.submit 'Salvar' %>
    </div>
<% end %>

app/views/softwares/edit.html.erb
<h1> Editando  </h1>
<div>
    <%= render 'softwares/form' %>
</div>
<%= button_to' Voltar', softwares_path, method: :get %>

app/views/softwares/index.html.erb
<h1>Lista de Softwares </h1>
<% @softwares.each do |s| %>  
    <%= s.name %>
    <%= s.version %>
    <%= button_to 'Editar', edit_software_path(s.id), method: :get %>
    <%= button_to 'Delete', software_path(s), method: :delete  %>    
<% end %><bR>
<%= button_to 'voltar ', root_path, method: :get  %>

app/views/softwares/new.html.erb
<h1> Cadastro Software </h1>

<div>
  <%= render 'softwares/form' %>
</div>

app/views/softwares/show.html.erb
<h1> Test show </h1>

<%= @software.name %> - <%= @software.version %>
<%= button_to'Editar', edit_software_path, method: :get %>